-- Item Checker · Supabase setup
-- Paste this whole file into Supabase → SQL Editor → New query, then click Run.
-- Safe to run more than once.

-- Items (same columns as the local SQLite table)
create table if not exists public.items (
  id              bigint generated by default as identity primary key,
  item_name       text        not null,
  sku             text        not null,
  physical_stock  integer     not null default 0 check (physical_stock  >= 0),
  committed_stock integer     not null default 0 check (committed_stock >= 0),
  active          smallint    not null default 1 check (active in (0, 1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- SKUs are unique and not case-sensitive (HC-001 = hc-001)
create unique index if not exists items_sku_nocase on public.items (lower(sku));

create or replace function public.items_touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists items_touch_updated_at on public.items;
create trigger items_touch_updated_at before update on public.items
  for each row execute function public.items_touch_updated_at();

-- Change counter: the apps poll this one number to know when to reload the list.
create table if not exists public.sync_state (
  id      int    primary key default 1 check (id = 1),
  version bigint not null default 0
);
insert into public.sync_state (id, version) values (1, 0) on conflict (id) do nothing;

create or replace function public.items_bump_version() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update public.sync_state set version = version + 1 where id = 1;
  return null;
end $$;

drop trigger if exists items_bump_version on public.items;
create trigger items_bump_version after insert or update or delete on public.items
  for each statement execute function public.items_bump_version();

-- Access: only signed-in users. Nobody can read or change anything without logging in.
alter table public.items      enable row level security;
alter table public.sync_state enable row level security;

drop policy if exists "signed-in users read items"   on public.items;
drop policy if exists "signed-in users add items"    on public.items;
drop policy if exists "signed-in users edit items"   on public.items;
drop policy if exists "signed-in users delete items" on public.items;
drop policy if exists "signed-in users read version" on public.sync_state;

create policy "signed-in users read items"   on public.items for select to authenticated using (true);
create policy "signed-in users add items"    on public.items for insert to authenticated with check (true);
create policy "signed-in users edit items"   on public.items for update to authenticated using (true) with check (true);
create policy "signed-in users delete items" on public.items for delete to authenticated using (true);
create policy "signed-in users read version" on public.sync_state for select to authenticated using (true);

revoke all on public.items, public.sync_state from anon;
grant select, insert, update, delete on public.items to authenticated;
grant select on public.sync_state to authenticated;
grant usage on sequence public.items_id_seq to authenticated;
